name: moor_flutter_poc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $runner build
  mobx_watch: $clean & $get & $runner watch
  mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+3
  flutter_modular: ^2.0.1
  moor_flutter: ^4.0.0
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
dev_dependencies:
  mockito: ^4.1.1+1
  build_runner: ^1.10.1
  moor_generator: ^4.3.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
